import Header from "./Components/Header";
import AuthProvider from "./Context/AuthContext";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main>
            <Header />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
export default RootLayout